from pydantic import BaseModel, Field
from typing import List

class ChatQueryRequest(BaseModel):
    session_id: str = Field(..., description="Unique user session identifier for Redis memory tracking")
    query: str = Field(..., description="The conversational text question or statement from the user")

class ChatQueryResponse(BaseModel):
    response: str = Field(..., description="The text reply generated by the local Qwen model")
    retrieved_context: List[str] = Field(..., description="The factual text blocks matched from Qdrant vectors")